name: 'GCP Docker Configuration'
description: 'Configure Docker for GCP Artifact Registry'

inputs:
  docker-registry:
    description: 'Docker registry URL'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure Docker for GCP Artifact Registry
      shell: bash
      run: |
        bash .github/scripts/configure-docker-artifact-registry.sh
      env:
        DOCKER_REGISTRY: ${{ inputs.docker-registry }}

