name: 'Detect Maven Module'
description: 'Detect Maven module path based on pattern and changed files'

inputs:
  module_path:
    description: 'Module path pattern (e.g., **-domain/**-presentation)'
    required: false
  module_pattern:
    description: 'Default module pattern (e.g., **/presentation/**)'
    required: false
    default: '**/presentation/**'

outputs:
  module_path:
    description: 'Detected module path'
    value: ${{ steps.detect.outputs.module_path }}

runs:
  using: 'composite'
  steps:
    - name: Detect module
      id: detect
      shell: bash
      run: |
        # Use module_path as pattern if provided, otherwise use module_pattern
        if [ -n "${{ inputs.module_path }}" ]; then
          MODULE_PATTERN="${{ inputs.module_path }}"
          echo "Using module_path pattern: $MODULE_PATTERN"
        else
          MODULE_PATTERN="${{ inputs.module_pattern }}"
          echo "Using module_pattern: $MODULE_PATTERN"
        fi
        
        # Try to get changed files from the event
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          # For PRs, compare with base branch
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          CHANGED_FILES=$(git diff --name-only origin/$BASE_REF...HEAD 2>/dev/null || echo "")
        elif [ "${{ github.event_name }}" == "push" ]; then
          # For pushes, compare with previous commit
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || echo "")
        else
          # For workflow_dispatch, check all modules
          CHANGED_FILES=""
        fi
        
        MODULE_PATH=""
        
        # Convert pattern to directory pattern for matching
        # Handle **/path/** patterns (e.g., **/presentation/** -> presentation)
        if [[ "$MODULE_PATTERN" == *"/"* ]]; then
          DIR_PATTERN=$(echo "$MODULE_PATTERN" | sed 's|\*\*/||' | sed 's|/\*\*||')
        else
          # Handle glob patterns (e.g., **-domain/**-presentation -> *-domain/*-presentation)
          DIR_PATTERN=$(echo "$MODULE_PATTERN" | sed 's|\*\*||g' | sed 's|/||g')
        fi
        
        # Find the module that changed
        if [ -n "$CHANGED_FILES" ]; then
          for file in $CHANGED_FILES; do
            # Match files against the pattern
            if [[ "$MODULE_PATTERN" == *"/"* ]]; then
              # Path-based pattern (e.g., **/presentation/**)
              if [[ $file == *"$DIR_PATTERN"* ]]; then
                # Extract module path
                MODULE_PATH=$(echo "$file" | sed -E "s|([^/]+/[^/]+/$DIR_PATTERN)/.*|\1|")
                if [ -f "$MODULE_PATH/pom.xml" ]; then
                  break
                fi
              fi
            else
              # Glob pattern (e.g., **-domain/**-presentation)
              # Convert pattern to shell glob: *-domain/*-presentation
              GLOB_PATTERN=$(echo "$DIR_PATTERN" | sed 's|\*\*|*|g')
              if [[ $file == $GLOB_PATTERN* ]] || [[ $file == *"/"$GLOB_PATTERN* ]]; then
                # Find the directory with pom.xml
                MODULE_PATH=$(dirname "$file")
                while [ "$MODULE_PATH" != "." ] && [ "$MODULE_PATH" != "/" ]; do
                  if [ -f "$MODULE_PATH/pom.xml" ]; then
                    break
                  fi
                  MODULE_PATH=$(dirname "$MODULE_PATH")
                done
                if [ -f "$MODULE_PATH/pom.xml" ]; then
                  break
                fi
              fi
            fi
          done
        fi
        
        # If no module detected from changes, find first module matching pattern
        if [ -z "$MODULE_PATH" ]; then
          if [[ "$MODULE_PATTERN" == *"/"* ]]; then
            # Path pattern (e.g., **/presentation/**)
            for dir in */*/$DIR_PATTERN; do
              if [ -d "$dir" ] && [ -f "$dir/pom.xml" ]; then
                MODULE_PATH="$dir"
                echo "Found module: $MODULE_PATH"
                break
              fi
            done
          else
            # Glob pattern (e.g., **-domain/**-presentation)
            GLOB_PATTERN=$(echo "$DIR_PATTERN" | sed 's|\*\*|*|g')
            for dir in */$GLOB_PATTERN; do
              if [ -d "$dir" ] && [ -f "$dir/pom.xml" ]; then
                MODULE_PATH="$dir"
                echo "Found module: $MODULE_PATH"
                break
              fi
            done
          fi
        fi
        
        if [ -z "$MODULE_PATH" ]; then
          echo "ERROR: Could not detect module"
          echo "Available directories:"
          ls -la
          exit 1
        fi
        
        # Verify pom.xml exists
        if [ ! -f "$MODULE_PATH/pom.xml" ]; then
          echo "ERROR: pom.xml not found at $MODULE_PATH/pom.xml"
          exit 1
        fi
        
        echo "module_path=$MODULE_PATH" >> $GITHUB_OUTPUT
        echo "✅ Detected module: $MODULE_PATH"

