name: 'GCP Authentication'
description: 'Authenticate to Google Cloud and set up Cloud SDK'

inputs:
  gcp-credentials:
    description: 'GCP service account credentials JSON'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp-credentials }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

